version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python /socialin/backend/manage.py wait_for_db &&
             python /socialin/backend/manage.py migrate &&
             python /socialin/backend/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./socialin:/socialin
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=somethingthatshouldbechanged
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=55552222
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=55552222
      
